wallet=elm_wallet
rpcport=19892
daemon=1
deprecatedrpc=create_bdb
rpcuser=your_rpc_username
rpcpassword=your_rpcpassword
maxconnections=10
server=1
upnp=1
spentindex=1
txindex=1
staking=0
addnode=127.0.0.1
